server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # 1. 기존 HTML 정적 페이지 (v3 고양이 화면)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # 2. 추가: /api/로 들어오는 요청은 옆동네 FastAPI(8000번)로 보낸다!
    location /api/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
