server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # 1. 기존 v3 고양이 화면 (Nginx 인스턴스 내부 파일)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # 2. 다른 인스턴스(10.0.12.35)의 FastAPI로 요청 전달
    location /api/ {
        # 'localhost' 대신 세훈 님의 프라이빗 IP 입력!
        proxy_pass http://10.0.12.35:8000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
