server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # 우리가 HTML 파일을 복사해 넣은 경로입니다.
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # 에러 페이지 설정 (선택 사항)
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
